@echo off
echo Starting AI Coloring Page Generator...
echo.
echo Opening WSL and starting the server...
wsl -d Ubuntu -e bash -c "cd /mnt/c/Users/mtdew/SuperClaude/image-generator-app && node serve.js"
pause